#!/usr/bin/env python3
"""
gen_syntax_ref.py - regenerate references/scratchblocks-syntax.md.

The supported-block table is generated straight from the BLOCKS and ALIASES
tables in make_sb3.py, so the reference can never claim a block the compiler
does not accept. Run this after adding a block:

    python3 skills/scratch-lab-generator/scripts/gen_syntax_ref.py
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SKILL = os.path.dirname(HERE)
sys.path.insert(0, HERE)

import make_sb3 as m  # noqa: E402

CATEGORIES = [
    ("Events", ["event_"]),
    ("Motion", ["motion_"]),
    ("Pen", ["pen_"]),
    ("Control", ["control_"]),
    ("Looks", ["looks_"]),
    ("Variables", ["data_"]),
    ("Operators", ["operator_"]),
    ("Sensing", ["sensing_"]),
]

# Extra guidance printed under a category table.
CATEGORY_NOTES = {
    "Control": (
        "`if % then else` is the compiler's internal name for the two-branch "
        "form; you never type it. Write `if <...> then`, put `else` on its own "
        "line, and close with `end` - the compiler promotes the block for you."
    ),
    "Pen": (
        "Any pen block adds `\"extensions\": [\"pen\"]` to the generated "
        "project, so a student opening the `.sb3` finds the Pen category "
        "already loaded."
    ),
}

HEADER = '''---
name: scratchblocks-syntax
description: The scratchblocks text syntax accepted by make_sb3.py, and the exact block vocabulary a generated lab may use.
---

<!-- Generated by scripts/gen_syntax_ref.py from the BLOCKS table in
     make_sb3.py. Do not edit the block tables by hand. -->

# Block Source Syntax

Every lab's block programs are written in **scratchblocks** text - the same
markup the Scratch Wiki uses. One `.txt` file per program drives two outputs:

- the block diagram rendered on the lab page (`<pre class="blocks">`)
- the downloadable `.sb3` program, compiled by `scripts/make_sb3.py`

Because both come from the same file, the picture a student sees and the
project they open can never disagree.

## Writing rules

1. **One block per line.** Leading whitespace is ignored by the compiler, but
   indent the body of a C-block anyway so the source stays readable.
2. **C-blocks close with `end`.** `repeat`, `forever`, `if`, `if/else`, and
   `repeat until` all need a matching `end`. `else` sits on its own line.
3. **Blank lines separate scripts.** Two scripts in one file become two
   separate stacks in the project.
4. **Operand brackets carry meaning**, exactly as in Scratch:
   - `(100)` - a number or a reporter slot
   - `[text]` - a text slot
   - `[choice v]` - a dropdown
   - `[#ff8800]` - a colour
   - `<...>` - a boolean slot
5. **Spacing disambiguates `<` and `>`.** `<(x) > (50)>` is a
   greater-than inside a boolean: the operator has spaces around it, the
   brackets do not. Write comparisons that way and nesting resolves correctly.
6. **Anything in round brackets that is not a number, a known reporter, or a
   custom-block parameter becomes a variable**, and the compiler creates that
   variable in the project automatically. `set [angle v] to (90)` followed by
   `turn cw (angle) degrees` is all you need - there is no declaration step.
7. **Comments** start with `//` and run to the end of the line.
8. **Escape angle brackets in `index.md`.** Inside `<pre class="blocks">`,
   write `&lt;` and `&gt;` so the browser's HTML parser does not swallow a
   boolean. The `.txt` file itself uses plain `<` and `>`;
   `scripts/check_lab.py --fix` applies the escaping when it syncs the page.
9. **An unrecognized line is an error, not a guess.** `make_sb3.py` fails the
   build and names the closest known block. If a lab needs a block that is not
   in the table below, add it to the `BLOCKS` table in `make_sb3.py` and rerun
   `gen_syntax_ref.py`.

## Custom blocks

```
define star (size) (points)
repeat (points)
  move (size) steps
  turn cw (144) degrees
end

when green flag clicked
star (100) (5)
```

`define` must appear in the same file as the calls to it. Round parameters
become "number or text" inputs (`%s`); angle-bracket parameters become boolean
inputs (`%b`). Inside the definition body a parameter name in round brackets
compiles to an argument reporter rather than a variable.

## Supported blocks

In a signature, `%` stands for any operand.
'''


def category_of(opcode):
    for name, prefixes in CATEGORIES:
        if any(opcode.startswith(p) for p in prefixes):
            return name
    return None


def main():
    buckets = {name: [] for name, _ in CATEGORIES}
    for sig, spec in m.BLOCKS.items():
        name = category_of(spec["opcode"])
        if name:
            buckets[name].append((sig, spec))

    aliases = {}
    for alias, canon in m.ALIASES.items():
        aliases.setdefault(canon, []).append(alias)

    out = [HEADER]
    total = 0
    for name, _ in CATEGORIES:
        entries = sorted(buckets[name])
        if not entries:
            continue
        total += len(entries)
        out.append("\n### %s\n" % name)
        out.append("| Write this | Opcode | Shape |")
        out.append("|------------|--------|-------|")
        for sig, spec in entries:
            shape = spec.get("shape", "stack")
            if spec.get("substacks"):
                shape += ", needs `end`"
            cell = "`%s`" % sig
            if aliases.get(sig):
                cell += "<br>also: " + ", ".join("`%s`" % a for a in sorted(aliases[sig]))
            out.append("| %s | `%s` | %s |" % (cell, spec["opcode"], shape))
        if name in CATEGORY_NOTES:
            out.append("\n%s" % CATEGORY_NOTES[name])

    path = os.path.join(SKILL, "references", "scratchblocks-syntax.md")
    open(path, "w").write("\n".join(out) + "\n")
    print("wrote %s (%d blocks in %d categories)"
          % (os.path.relpath(path), total,
             sum(1 for n, _ in CATEGORIES if buckets[n])))


if __name__ == "__main__":
    main()
